sFile$Voltage<-as.numeric(as.character(sFile$Voltage))
sFile$Global_reactive_power<-as.numeric(as.character(sFile$Global_reactive_power))
png(filename="plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(sFile$dateTime,sFile$Global_active_power,type="l",xlab="",ylab ="Global Active Power")
plot(sFile$dateTime,sFile$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(sFile$dateTime,sFile$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(sFile$dateTime,sFile$Sub_metering_2,type="l",col="red")
lines(sFile$dateTime,sFile$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty = "n")
plot(sFile$dateTime,sFile$Global_reactive_power,type="l",xlab="dat etime",ylab="Global_reactive_power")
dev.off()