sFile$Sub_metering_1<-as.numeric(as.character(sFile$Sub_metering_1))
sFile$Sub_metering_2<-as.numeric(as.character(sFile$Sub_metering_2))
sFile$Sub_metering_3<-as.numeric(as.character(sFile$Sub_metering_3))
png(filename="plot3.png", width = 480, height = 480, units = "px")
plot(sFile$dateTime,sFile$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(sFile$dateTime,sFile$Sub_metering_2,type="l",col="red")
lines(sFile$dateTime,sFile$Sub_metering_3,type="l",col="blue")
legend("topright",col=c("black","red","blue"),lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty = "n")
dev.off()